### ISSUE TITLE
Text placed into the X11 clipboard not available afterwards

### ISSUE THREAD

**Issue by jonasmalacofilho** [ArturKovacs/arboard#4] opened 2020-10-16 18:37 UTC
With `examples/hello_world.rs` and initial "some old contents" clipboard contents:

```
$ target/debug/examples/hello_world
Clipboard text was: some old content
But now the clipboard text should be: "Hello, world!"

$ target/debug/examples/hello_world
Clipboard text was: some old content
But now the clipboard text should be: "Hello, world!"

$ target/debug/examples/hello_world
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContentNotAvailable - "The clipboard contents were not available in the requested format or the clipboard is empty."', examples/hello_world.rs:5:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The first run appears to have no effect on the X11 clipboard; the second one does have some effect, but only to clear it.

Note that the panic in the third run is only a side effect: the example in question doesn't handle the case where the clipboard is empty.

After some debugging, it seems that `x11_clipboard_manager` is 0 during the `destruct` call, [preventing the handing off of the data](https://github.com/ArturKovacs/arboard/blob/2f3fde214745c09ed609a4316e661a3dfcf68b15/src/x11_clipboard.rs#L544-L557).

I'm not sure why the `x11_clipboard_manager != 0` condition is necessary, and if fact it seems that a `xcb_window_t` value of 0 (or `XCB_NONE`) is valid for other XCB calls; for example, in `xcb_set_selection_owner` it [means that the selection will have no owner](https://www.x.org/releases/X11R7.7/doc/man/man3/xcb_set_selection_owner.3.xhtml).

I experimented with removing this condition entirely (and the previous calls that only serve to fill in `x11_clipboard_manager`) and everything worked just fine, but I'm well aware that this doesn't mean anything, particularly when dealing with Xorg. : )

P.S. I first noticed the problem in 1.0.1, but I've been since working on top of the current HEAD.

**Comment by jonasmalacofilho** [comment] 2020-10-24 02:10
@ArturKovacs can you help me find the relevant documentation for fixing this?  I would love to help here, but I'm quite oblivious to how X11 actually works.

**Comment by ArturKovacs** [comment] 2020-10-24 08:50
> I would love to help here, but I'm quite oblivious to how X11 actually works.

Me too :D and I'm not even kidding. The X11 implementation is my attempt at porting https://github.com/dacap/clip to Rust. That aside, I just tested this and I couldn't reproduce this issue on my gnome desktop with neither of X11 or Wayland. But this of course is not too relevant for solving the issue.

Why David Capello put the check for the clipboard manager [there in the original](https://github.com/dacap/clip/blob/5377679fd32f977b32b51d83e0fdc027adcdfe78/clip_x11.cpp#L133) is not something I know. It seems to me that it would be perfectly reasonable to just try requesting the `SAVE_TARGETS` without checking for the existence of a clipboard manager. If there's an error at that point there isn't anything we could do anyways.

So right now I'm leaning towards just removing the check for the clipboard manager from there.

Before we do that though, could you try reproducing this, using clip. I guess the simples rout is to just get a copy of [`clip`](https://github.com/dacap/clip) then just create a `main.cpp` in clip's top directory with the following contents:

```cpp
// In main.cpp
#include "clip.h"
#include <cassert>
#include <iostream>

int main() {
  std::cout << "// C++" << std::endl;
  char* new_text = "Hello, World!";
  std::string value;
  bool result = clip::get_text(value);
  assert(result);
  std::cout << "Cliboard text was: " << value << std::endl;
  clip::set_text(new_text);
  std::cout << "But now the clipboard text should be: \"" << new_text << "\"" << std::endl;
}
```
Compile with

```
g++ main.cpp clip_x11.cpp clip.cpp image.cpp -lxcb -lpthread
```

Then execute with

```
./a.out
```

**Comment by jonasmalacofilho** [comment] 2020-10-25 03:07
Thanks for the directions!

I can reproduce this with `clip`, and a similar issue had already been reported there: dacap/clip#31.  In my case, it seems that I have a clipboard manager – Mutter – but it doesn't acquire the `CLIPBOARD_MANAGER` selection: [GNOME/mutter@952](GNOME/mutter/-/issues/952).

The issue mentions that's is unclear how much of clipboard manager spec, if at all, they plan to provide.  Currently, Mutter simply monitors for changes in ownership, and takes over when there's no owner left: [`src/core/meta-clipboard-manager.c#L148-156`](https://gitlab.gnome.org/GNOME/mutter/-/blob/a43821311b180d34b1299dd093cc6529dc8b743c/src/core/meta-clipboard-manager.c#L148-156).

So while simply ignoring the absence of a (spec-compliant) clipboard manager does work, I'm starting to think it's just a happy side effect.  I'm also curious if there's a cleaner way to support this style of clipboard persistence (GNOME is fairly popular after all), and how other applications are doing it.

By the way, before Mutter this functionality was provided in GNOME by gnome-settings-daemon ([GNOME/gnome-settings-daemon@106](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/106)); and at first glance it appeared to implement the SAVE_TARGETS mechanism per the spec.

P.S. I imagine KDE is doing something similar to Mutter, which could explain the clip issue.

**Comment by ArturKovacs** [comment] 2020-10-25 10:44
Hol' up a minute. I'm using GNOME (`echo $XDG_CURRENT_DESKTOP`) and you seem to be saying that you are using GNOME too. The about panel in settings reports GNOME version `3.28.2` for me. Are you using a newer or older version maybe?

I just stepped through `hello_world` and the `x11_clipboard_manager` for me is in fact *non-zero*. So for me, the `SAVE_TARGETS` conversion gets requested with that check in place.

> By the way, before Mutter this functionality was provided in GNOME by gnome-settings-daemon (GNOME/gnome-settings-daemon@106); and at first glance it appeared to implement the SAVE_TARGETS mechanism per the spec.

Yeah, that's my assessment as well ([starting from line 421](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/f0b38977e97687d668005c6ea85fa9121739a369#bc27015f858fe2b9610806c81381ff3a70b6da28_421_0) of gsd-clipboard-manager.c). But then the problem isn't really with save targets but it's the fact that your GNOME reports no clipboard manager while mine does, right?

> Mutter [...] takes over when there's no owner left

Except it doesn't apparently, as you demonstrated. I'm wondering if this function in Mutter only gets called when the `SAVE_TARGETS` is requested for a non-existent target.

I think at this point it's clear that the rabbit hole is deep and even if some window managers have a sub-optimal or incorrect implementation, I think this should be mitigated within arboard, because I wouldn't be comfortable waiting on a solution to get merged and released. Although I have to admit that it's fun to investigate.

All-in-all I would say that the most important question right now is: If we remove the check for a clipboard manager from there, is it going to produce undesirable behaviour on other systems?

On my setup removing the check seems to be fine and I don't see a reason why it wouldn't be fine elsewhere.

----

As you can see from the reference above, I also left a comment at the related issue at clip. Maybe sharing information could be beneficial for all parties.

**Comment by jonasmalacofilho** [comment] 2020-10-25 11:30
> The about panel in settings reports GNOME version 3.28.2 for me. Are you using a newer or older version maybe?

I'm running a newer version, 3.38.1.  It seems the clipboard code was removed from gnome-settings-daemon in GNOME 3.34.

> I'm wondering if this function in Mutter only gets called when the `SAVE_TARGETS` is requested for a non-existent target.

I think so, indirectly/somehow.  But I haven't managed to piece it together yet.

> I think this should be mitigated within arboard, because I wouldn't be comfortable waiting on a solution to get merged and released. Although I have to admit that it's fun to investigate.

I agree...  with both statements.

> All-in-all I would say that the most important question right now is: If we remove the check for a clipboard manager from there, is it going to produce undesirable behaviour on other systems?

I don't think so, for a few reasons:

- this wont change anything on systems with managers that announce themselves (by acquiring the corresponding selection)
- on systems without them and without a Mutter-like manager, converting the selection will fail but (per the spec) we should simply ignore the error and exit<sup>1</sup>
- GLFW (I simply picked one popular program I use – kitty terminal – and went down the surprisingly shallow rabbit hole of dependencies) also [doesn't check for a manager](https://github.com/glfw/glfw/blob/0cc13ceafc233cb0bc95c8b3ff8152ee75893bf9/src/x11_window.c#L1888-L1934) before converting the selection

That said, I need a substantial delay for the test bellow to pass (after removing the check).  It's not a big practical problem (the application is exiting after all), but it suggests that we could still be missing something.

```rust
let mut ctx = Clipboard::new().unwrap();
let text = "some string2";
ctx.set_text(text.to_owned()).unwrap();
assert_eq!(ctx.get_text().unwrap(), text);

drop(ctx);

use std::time::Duration;
std::thread::sleep(Duration::from_millis(10));

let mut ctx = Clipboard::new().unwrap();
assert_eq!(ctx.get_text().unwrap(), text);
```

<sup>1</sup> But shouldn't we check/handle errors from `convert_selection` in `get_data_from_selection_owner` in other scenarios?

**Comment by ArturKovacs** [comment] 2020-10-25 13:41
Okay so let's just remove the check for a manager.

> But shouldn't we check/handle errors from convert_selection in get_data_from_selection_owner in other scenarios?

Haha, yeah we prooobably should.

> That said, I need a substantial delay for the test bellow to pass 

Hmm that is odd. But given the quirkiness of the x11 clipboard protocoll I can easily imagine that this is caused by a delay in the clipboard manager that's there to conform the protocoll. I'm not really worried about this.

**Comment by jonasmalacofilho** [comment] 2020-10-25 23:18
> Haha, yeah we prooobably should.

: )

I'll take a look at this while I work on #6.

**Closed** 2020-10-28 21:58 UTC
Labels: bug
